apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrywja0606.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 8080
        env:
        - name: WEB_PORT
          value: "8080"
        - name: WEB_SERVER_BASE_URI
          value: "http://0.0.0.0"
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: CONFIG_FILES_PATH
          value: "/secrets"
        envFrom:
        - secretRef:
            name: db-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: poi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registrywja0606.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        envFrom:
        - secretRef:
            name: db-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: api
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: user-java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registrywja0606.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: OPENAPI_DOCS_URI
          value: "http://changeme"
        envFrom:
        - secretRef:
            name: db-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: trips
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registrywja0606.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        envFrom:
        - secretRef:
            name: db-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: api
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: userprofile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registrywja0606.azurecr.io/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: tripviewer