apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: "registrywja0606.azurecr.io/tripinsights/poi:1.0"
        volumeMounts:
        - name: secrets
          mountPath: /kvmnt
          readOnly: true
        ports:
        - containerPort: 8080
        env:
        - name: WEB_PORT
          value: "8080"
        - name: WEB_SERVER_BASE_URI
          value: "http://0.0.0.0"
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
      volumes:
      - name: secrets
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds                             # [OPTIONAL] not required if using Pod Identity
          options:
            usepodidentity: "false"                   # [OPTIONAL] if not provided, will default to "false"
            usevmmanagedidentity: "false"             # [OPTIONAL new in version >= v0.0.15] if not provided, will default to "false"
            vmmanagedidentityclientid: "clientid"     # [OPTIONAL new in version >= v0.0.15] use the client id to specify which user assigned managed identity to use, leave empty to use system assigned managed identity
            keyvaultname: "rbac-aks-kv"              # [REQUIRED] the name of the KeyVault
            keyvaultobjectnames: "SQL-USER;SQL-PASSWORD;SQL-SERVER;SQL-DBNAME"         # [REQUIRED] list of KeyVault object names (semi-colon separated)
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER;SQL_DBNAME"      # [OPTIONAL] list of KeyVault object aliases
            keyvaultobjecttypes: "secret;secret;secret;secret"               # [REQUIRED] list of KeyVault object types: secret, key, cert
            resourcegroup: "teamResources"        # [REQUIRED for version < v0.0.14] the resource group of the KeyVault
            subscriptionid: "05ee0654-5f89-4783-b11a-39860a372718"                 # [REQUIRED for version < v0.0.14] the subscription ID of the KeyVault
            tenantid: "500cf2dc-1450-4b7d-a759-c5a1ebe1308f"                    # [REQUIRED] the tenant ID of the KeyVault
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: poi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registrywja0606.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
      volumes:
      - name: secrets
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds                             # [OPTIONAL] not required if using Pod Identity
          options:
            usepodidentity: "false"                   # [OPTIONAL] if not provided, will default to "false"
            usevmmanagedidentity: "false"             # [OPTIONAL new in version >= v0.0.15] if not provided, will default to "false"
            vmmanagedidentityclientid: "clientid"     # [OPTIONAL new in version >= v0.0.15] use the client id to specify which user assigned managed identity to use, leave empty to use system assigned managed identity
            keyvaultname: "rbac-aks-kv"              # [REQUIRED] the name of the KeyVault
            keyvaultobjectnames: "SQL-USER;SQL-PASSWORD;SQL-SERVER;SQL-DBNAME"         # [REQUIRED] list of KeyVault object names (semi-colon separated)
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER;SQL_DBNAME"      # [OPTIONAL] list of KeyVault object aliases
            keyvaultobjecttypes: "secret;secret;secret;secret"               # [REQUIRED] list of KeyVault object types: secret, key, cert
            resourcegroup: "teamResources"        # [REQUIRED for version < v0.0.14] the resource group of the KeyVault
            subscriptionid: "05ee0654-5f89-4783-b11a-39860a372718"                 # [REQUIRED for version < v0.0.14] the subscription ID of the KeyVault
            tenantid: "500cf2dc-1450-4b7d-a759-c5a1ebe1308f"                    # [REQUIRED] the tenant ID of the KeyVault
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: api
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: user-java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registrywja0606.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: OPENAPI_DOCS_URI
          value: "http://changeme"
      volumes:
      - name: secrets
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds                             # [OPTIONAL] not required if using Pod Identity
          options:
            usepodidentity: "false"                   # [OPTIONAL] if not provided, will default to "false"
            usevmmanagedidentity: "false"             # [OPTIONAL new in version >= v0.0.15] if not provided, will default to "false"
            vmmanagedidentityclientid: "clientid"     # [OPTIONAL new in version >= v0.0.15] use the client id to specify which user assigned managed identity to use, leave empty to use system assigned managed identity
            keyvaultname: "rbac-aks-kv"              # [REQUIRED] the name of the KeyVault
            keyvaultobjectnames: "SQL-USER;SQL-PASSWORD;SQL-SERVER;SQL-DBNAME"         # [REQUIRED] list of KeyVault object names (semi-colon separated)
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER;SQL_DBNAME"      # [OPTIONAL] list of KeyVault object aliases
            keyvaultobjecttypes: "secret;secret;secret;secret"               # [REQUIRED] list of KeyVault object types: secret, key, cert
            resourcegroup: "teamResources"        # [REQUIRED for version < v0.0.14] the resource group of the KeyVault
            subscriptionid: "05ee0654-5f89-4783-b11a-39860a372718"                 # [REQUIRED for version < v0.0.14] the subscription ID of the KeyVault
            tenantid: "500cf2dc-1450-4b7d-a759-c5a1ebe1308f"                    # [REQUIRED] the tenant ID of the KeyVault
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: trips
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registrywja0606.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
      volumes:
      - name: secrets
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds                             # [OPTIONAL] not required if using Pod Identity
          options:
            usepodidentity: "false"                   # [OPTIONAL] if not provided, will default to "false"
            usevmmanagedidentity: "false"             # [OPTIONAL new in version >= v0.0.15] if not provided, will default to "false"
            vmmanagedidentityclientid: "clientid"     # [OPTIONAL new in version >= v0.0.15] use the client id to specify which user assigned managed identity to use, leave empty to use system assigned managed identity
            keyvaultname: "rbac-aks-kv"              # [REQUIRED] the name of the KeyVault
            keyvaultobjectnames: "SQL-USER;SQL-PASSWORD;SQL-SERVER;SQL-DBNAME"         # [REQUIRED] list of KeyVault object names (semi-colon separated)
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER;SQL_DBNAME"      # [OPTIONAL] list of KeyVault object aliases
            keyvaultobjecttypes: "secret;secret;secret;secret"               # [REQUIRED] list of KeyVault object types: secret, key, cert
            resourcegroup: "teamResources"        # [REQUIRED for version < v0.0.14] the resource group of the KeyVault
            subscriptionid: "05ee0654-5f89-4783-b11a-39860a372718"                 # [REQUIRED for version < v0.0.14] the subscription ID of the KeyVault
            tenantid: "500cf2dc-1450-4b7d-a759-c5a1ebe1308f"                    # [REQUIRED] the tenant ID of the KeyVault
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: api
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: userprofile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registrywja0606.azurecr.io/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: tripviewer